/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedFollowUpsRouteImport } from './routes/_authenticated/follow-ups'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedApprovalsIndexRouteImport } from './routes/_authenticated/approvals/index'
import { Route as AuthenticatedApprovalsApprovalIdRouteImport } from './routes/_authenticated/approvals/$approvalId'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedInspectionsIndexRouteImport } from './routes/_authenticated/inspections/index'
import { Route as AuthenticatedMaintenanceIndexRouteImport } from './routes/_authenticated/maintenance/index'
import { Route as AuthenticatedMaintenanceAiAgentRouteImport } from './routes/_authenticated/maintenance/ai-agent'
import { Route as AuthenticatedMaintenanceCatalogRouteImport } from './routes/_authenticated/maintenance/catalog'
import { Route as AuthenticatedMaintenanceJobsRouteImport } from './routes/_authenticated/maintenance/jobs'
import { Route as AuthenticatedMaintenanceReportsRouteImport } from './routes/_authenticated/maintenance/reports'
import { Route as AuthenticatedQuotationsIndexRouteImport } from './routes/_authenticated/quotations/index'
import { Route as AuthenticatedQuotationsCompareRouteImport } from './routes/_authenticated/quotations/compare'

import { Route as AuthenticatedProviderCoordinationIndexRouteImport } from './routes/_authenticated/provider-coordination/index'
import { Route as AuthenticatedProviderCoordinationCalendarRouteImport } from './routes/_authenticated/provider-coordination/calendar'
import { Route as AuthenticatedProviderCoordinationMatchingRouteImport } from './routes/_authenticated/provider-coordination/matching'

import { Route as AuthenticatedIncidentsIndexRouteImport } from './routes/_authenticated/incidents/index'

import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedProviderCoordinationProvidersIndexRouteImport } from './routes/_authenticated/provider-coordination/providers/index'
import { Route as AuthenticatedProviderCoordinationProvidersProviderIdRouteImport } from './routes/_authenticated/provider-coordination/providers/$providerId'
import { Route as AuthenticatedProviderCoordinationRepresentativesIndexRouteImport } from './routes/_authenticated/provider-coordination/representatives/index'
import { Route as AuthenticatedProviderCoordinationRepresentativesRepresentativeIdRouteImport } from './routes/_authenticated/provider-coordination/representatives/$representativeId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowUpsRoute = AuthenticatedFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApprovalsIndexRoute =
  AuthenticatedApprovalsIndexRouteImport.update({
    id: '/approvals/',
    path: '/approvals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApprovalsApprovalIdRoute =
  AuthenticatedApprovalsApprovalIdRouteImport.update({
    id: '/approvals/$approvalId',
    path: '/approvals/$approvalId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionsIndexRoute =
  AuthenticatedInspectionsIndexRouteImport.update({
    id: '/inspections/',
    path: '/inspections/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaintenanceIndexRoute =
  AuthenticatedMaintenanceIndexRouteImport.update({
    id: '/maintenance/',
    path: '/maintenance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaintenanceAiAgentRoute =
  AuthenticatedMaintenanceAiAgentRouteImport.update({
    id: '/maintenance/ai-agent',
    path: '/maintenance/ai-agent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaintenanceCatalogRoute =
  AuthenticatedMaintenanceCatalogRouteImport.update({
    id: '/maintenance/catalog',
    path: '/maintenance/catalog',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaintenanceJobsRoute =
  AuthenticatedMaintenanceJobsRouteImport.update({
    id: '/maintenance/jobs',
    path: '/maintenance/jobs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaintenanceReportsRoute =
  AuthenticatedMaintenanceReportsRouteImport.update({
    id: '/maintenance/reports',
    path: '/maintenance/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotationsIndexRoute =
  AuthenticatedQuotationsIndexRouteImport.update({
    id: '/quotations/',
    path: '/quotations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotationsCompareRoute =
  AuthenticatedQuotationsCompareRouteImport.update({
    id: '/quotations/compare',
    path: '/quotations/compare',
    getParentRoute: () => AuthenticatedRouteRoute,

const AuthenticatedProviderCoordinationIndexRoute =
  AuthenticatedProviderCoordinationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProviderCoordinationRouteRoute,
  } as any)
const AuthenticatedProviderCoordinationCalendarRoute =
  AuthenticatedProviderCoordinationCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedProviderCoordinationRouteRoute,
  } as any)
const AuthenticatedProviderCoordinationMatchingRoute =
  AuthenticatedProviderCoordinationMatchingRouteImport.update({
    id: '/matching',
    path: '/matching',
    getParentRoute: () => AuthenticatedProviderCoordinationRouteRoute,

const AuthenticatedIncidentsIndexRoute =
  AuthenticatedIncidentsIndexRouteImport.update({
    id: '/incidents/',
    path: '/incidents/',
    getParentRoute: () => AuthenticatedRouteRoute,

  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedProviderCoordinationProvidersIndexRoute =
  AuthenticatedProviderCoordinationProvidersIndexRouteImport.update({
    id: '/providers/',
    path: '/providers/',
    getParentRoute: () => AuthenticatedProviderCoordinationRouteRoute,
  } as any)
const AuthenticatedProviderCoordinationProvidersProviderIdRoute =
  AuthenticatedProviderCoordinationProvidersProviderIdRouteImport.update({
    id: '/providers/$providerId',
    path: '/providers/$providerId',
    getParentRoute: () => AuthenticatedProviderCoordinationRouteRoute,
  } as any)
const AuthenticatedProviderCoordinationRepresentativesIndexRoute =
  AuthenticatedProviderCoordinationRepresentativesIndexRouteImport.update({
    id: '/representatives/',
    path: '/representatives/',
    getParentRoute: () => AuthenticatedProviderCoordinationRouteRoute,
  } as any)
const AuthenticatedProviderCoordinationRepresentativesRepresentativeIdRoute =
  AuthenticatedProviderCoordinationRepresentativesRepresentativeIdRouteImport.update(
    {
      id: '/representatives/$representativeId',
      path: '/representatives/$representativeId',
      getParentRoute: () => AuthenticatedProviderCoordinationRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/provider-coordination': typeof AuthenticatedProviderCoordinationRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/approvals/$approvalId': typeof AuthenticatedApprovalsApprovalIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/maintenance/ai-agent': typeof AuthenticatedMaintenanceAiAgentRoute
  '/maintenance/catalog': typeof AuthenticatedMaintenanceCatalogRoute
  '/maintenance/jobs': typeof AuthenticatedMaintenanceJobsRoute
  '/maintenance/reports': typeof AuthenticatedMaintenanceReportsRoute
  '/quotations/compare': typeof AuthenticatedQuotationsCompareRoute
  '/provider-coordination/calendar': typeof AuthenticatedProviderCoordinationCalendarRoute
  '/provider-coordination/matching': typeof AuthenticatedProviderCoordinationMatchingRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/inspections/': typeof AuthenticatedInspectionsIndexRoute
  '/maintenance/': typeof AuthenticatedMaintenanceIndexRoute
  '/quotations/': typeof AuthenticatedQuotationsIndexRoute
  '/approvals/': typeof AuthenticatedApprovalsIndexRoute

  '/provider-coordination/': typeof AuthenticatedProviderCoordinationIndexRoute

  '/assets/': typeof AuthenticatedAssetsIndexRoute
  '/incidents/': typeof AuthenticatedIncidentsIndexRoute

  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/provider-coordination/providers/$providerId': typeof AuthenticatedProviderCoordinationProvidersProviderIdRoute
  '/provider-coordination/representatives/$representativeId': typeof AuthenticatedProviderCoordinationRepresentativesRepresentativeIdRoute
  '/provider-coordination/providers/': typeof AuthenticatedProviderCoordinationProvidersIndexRoute
  '/provider-coordination/representatives/': typeof AuthenticatedProviderCoordinationRepresentativesIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/': typeof AuthenticatedIndexRoute
  '/approvals/$approvalId': typeof AuthenticatedApprovalsApprovalIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/maintenance/ai-agent': typeof AuthenticatedMaintenanceAiAgentRoute
  '/maintenance/catalog': typeof AuthenticatedMaintenanceCatalogRoute
  '/maintenance/jobs': typeof AuthenticatedMaintenanceJobsRoute
  '/maintenance/reports': typeof AuthenticatedMaintenanceReportsRoute
  '/quotations/compare': typeof AuthenticatedQuotationsCompareRoute
  '/provider-coordination/calendar': typeof AuthenticatedProviderCoordinationCalendarRoute
  '/provider-coordination/matching': typeof AuthenticatedProviderCoordinationMatchingRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/inspections': typeof AuthenticatedInspectionsIndexRoute
  '/maintenance': typeof AuthenticatedMaintenanceIndexRoute
  '/quotations': typeof AuthenticatedQuotationsIndexRoute
  '/approvals': typeof AuthenticatedApprovalsIndexRoute

  '/provider-coordination': typeof AuthenticatedProviderCoordinationIndexRoute

  '/assets': typeof AuthenticatedAssetsIndexRoute
  '/incidents': typeof AuthenticatedIncidentsIndexRoute

  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/provider-coordination/providers/$providerId': typeof AuthenticatedProviderCoordinationProvidersProviderIdRoute
  '/provider-coordination/representatives/$representativeId': typeof AuthenticatedProviderCoordinationRepresentativesRepresentativeIdRoute
  '/provider-coordination/providers': typeof AuthenticatedProviderCoordinationProvidersIndexRoute
  '/provider-coordination/representatives': typeof AuthenticatedProviderCoordinationRepresentativesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/provider-coordination': typeof AuthenticatedProviderCoordinationRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/approvals/$approvalId': typeof AuthenticatedApprovalsApprovalIdRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/maintenance/ai-agent': typeof AuthenticatedMaintenanceAiAgentRoute
  '/_authenticated/maintenance/catalog': typeof AuthenticatedMaintenanceCatalogRoute
  '/_authenticated/maintenance/jobs': typeof AuthenticatedMaintenanceJobsRoute
  '/_authenticated/maintenance/reports': typeof AuthenticatedMaintenanceReportsRoute
  '/_authenticated/quotations/compare': typeof AuthenticatedQuotationsCompareRoute
  '/_authenticated/provider-coordination/calendar': typeof AuthenticatedProviderCoordinationCalendarRoute
  '/_authenticated/provider-coordination/matching': typeof AuthenticatedProviderCoordinationMatchingRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/inspections/': typeof AuthenticatedInspectionsIndexRoute
  '/_authenticated/maintenance/': typeof AuthenticatedMaintenanceIndexRoute
  '/_authenticated/quotations/': typeof AuthenticatedQuotationsIndexRoute
  '/_authenticated/approvals/': typeof AuthenticatedApprovalsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/provider-coordination/providers/$providerId': typeof AuthenticatedProviderCoordinationProvidersProviderIdRoute
  '/_authenticated/provider-coordination/representatives/$representativeId': typeof AuthenticatedProviderCoordinationRepresentativesRepresentativeIdRoute
  '/_authenticated/provider-coordination/providers/': typeof AuthenticatedProviderCoordinationProvidersIndexRoute
  '/_authenticated/provider-coordination/representatives/': typeof AuthenticatedProviderCoordinationRepresentativesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/provider-coordination'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/audit-logs'
    | '/follow-ups'
    | '/approvals/$approvalId'
    | '/errors/$error'
    | '/maintenance/ai-agent'
    | '/maintenance/catalog'
    | '/maintenance/jobs'
    | '/maintenance/reports'
    | '/quotations/compare'
    | '/provider-coordination/calendar'
    | '/provider-coordination/matching'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/inspections/'
    | '/maintenance/'
    | '/quotations/'
    | '/approvals/'
    | '/settings/'
    | '/provider-coordination/providers/$providerId'
    | '/provider-coordination/representatives/$representativeId'
    | '/provider-coordination/providers/'
    | '/provider-coordination/representatives/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/audit-logs'
    | '/follow-ups'
    | '/'
    | '/approvals/$approvalId'
    | '/errors/$error'
    | '/maintenance/ai-agent'
    | '/maintenance/catalog'
    | '/maintenance/jobs'
    | '/maintenance/reports'
    | '/quotations/compare'
    | '/provider-coordination/calendar'
    | '/provider-coordination/matching'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/inspections'
    | '/maintenance'
    | '/quotations'
    | '/approvals'
    | '/settings'
    | '/provider-coordination/providers/$providerId'
    | '/provider-coordination/representatives/$representativeId'
    | '/provider-coordination/providers'
    | '/provider-coordination/representatives'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/provider-coordination'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/audit-logs'
    | '/_authenticated/follow-ups'
    | '/_authenticated/'
    | '/_authenticated/approvals/$approvalId'
    | '/_authenticated/errors/$error'
    | '/_authenticated/maintenance/ai-agent'
    | '/_authenticated/maintenance/catalog'
    | '/_authenticated/maintenance/jobs'
    | '/_authenticated/maintenance/reports'
    | '/_authenticated/quotations/compare'
    | '/_authenticated/provider-coordination/calendar'
    | '/_authenticated/provider-coordination/matching'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/inspections/'
    | '/_authenticated/maintenance/'
    | '/_authenticated/quotations/'
    | '/_authenticated/approvals/'
    | '/_authenticated/settings/'
    | '/_authenticated/provider-coordination/providers/$providerId'
    | '/_authenticated/provider-coordination/representatives/$representativeId'
    | '/_authenticated/provider-coordination/providers/'
    | '/_authenticated/provider-coordination/representatives/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/follow-ups': {
      id: '/_authenticated/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof AuthenticatedFollowUpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals/': {
      id: '/_authenticated/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof AuthenticatedApprovalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals/$approvalId': {
      id: '/_authenticated/approvals/$approvalId'
      path: '/approvals/$approvalId'
      fullPath: '/approvals/$approvalId'
      preLoaderRoute: typeof AuthenticatedApprovalsApprovalIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspections/': {
      id: '/_authenticated/inspections/'
      path: '/inspections'
      fullPath: '/inspections/'
      preLoaderRoute: typeof AuthenticatedInspectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance/': {
      id: '/_authenticated/maintenance/'
      path: '/maintenance'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof AuthenticatedMaintenanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance/ai-agent': {
      id: '/_authenticated/maintenance/ai-agent'
      path: '/maintenance/ai-agent'
      fullPath: '/maintenance/ai-agent'
      preLoaderRoute: typeof AuthenticatedMaintenanceAiAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance/catalog': {
      id: '/_authenticated/maintenance/catalog'
      path: '/maintenance/catalog'
      fullPath: '/maintenance/catalog'
      preLoaderRoute: typeof AuthenticatedMaintenanceCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance/jobs': {
      id: '/_authenticated/maintenance/jobs'
      path: '/maintenance/jobs'
      fullPath: '/maintenance/jobs'
      preLoaderRoute: typeof AuthenticatedMaintenanceJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance/reports': {
      id: '/_authenticated/maintenance/reports'
      path: '/maintenance/reports'
      fullPath: '/maintenance/reports'
      preLoaderRoute: typeof AuthenticatedMaintenanceReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/': {
      id: '/_authenticated/quotations/'
      path: '/quotations'
      fullPath: '/quotations/'
      preLoaderRoute: typeof AuthenticatedQuotationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/compare': {
      id: '/_authenticated/quotations/compare'
      path: '/quotations/compare'
      fullPath: '/quotations/compare'
      preLoaderRoute: typeof AuthenticatedQuotationsCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute

    '/_authenticated/provider-coordination/': {
      id: '/_authenticated/provider-coordination/'
      path: '/'
      fullPath: '/provider-coordination/'
      preLoaderRoute: typeof AuthenticatedProviderCoordinationIndexRouteImport
      parentRoute: typeof AuthenticatedProviderCoordinationRouteRoute
    }
    '/_authenticated/provider-coordination/calendar': {
      id: '/_authenticated/provider-coordination/calendar'
      path: '/calendar'
      fullPath: '/provider-coordination/calendar'
      preLoaderRoute: typeof AuthenticatedProviderCoordinationCalendarRouteImport
      parentRoute: typeof AuthenticatedProviderCoordinationRouteRoute
    }
    '/_authenticated/provider-coordination/matching': {
      id: '/_authenticated/provider-coordination/matching'
      path: '/matching'
      fullPath: '/provider-coordination/matching'
      preLoaderRoute: typeof AuthenticatedProviderCoordinationMatchingRouteImport
      parentRoute: typeof AuthenticatedProviderCoordinationRouteRoute

    '/_authenticated/incidents/': {
      id: '/_authenticated/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof AuthenticatedIncidentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute

    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/provider-coordination/providers/': {
      id: '/_authenticated/provider-coordination/providers/'
      path: '/providers'
      fullPath: '/provider-coordination/providers/'
      preLoaderRoute: typeof AuthenticatedProviderCoordinationProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedProviderCoordinationRouteRoute
    }
    '/_authenticated/provider-coordination/providers/$providerId': {
      id: '/_authenticated/provider-coordination/providers/$providerId'
      path: '/providers/$providerId'
      fullPath: '/provider-coordination/providers/$providerId'
      preLoaderRoute: typeof AuthenticatedProviderCoordinationProvidersProviderIdRouteImport
      parentRoute: typeof AuthenticatedProviderCoordinationRouteRoute
    }
    '/_authenticated/provider-coordination/representatives/': {
      id: '/_authenticated/provider-coordination/representatives/'
      path: '/representatives'
      fullPath: '/provider-coordination/representatives/'
      preLoaderRoute: typeof AuthenticatedProviderCoordinationRepresentativesIndexRouteImport
      parentRoute: typeof AuthenticatedProviderCoordinationRouteRoute
    }
    '/_authenticated/provider-coordination/representatives/$representativeId': {
      id: '/_authenticated/provider-coordination/representatives/$representativeId'
      path: '/representatives/$representativeId'
      fullPath: '/provider-coordination/representatives/$representativeId'
      preLoaderRoute: typeof AuthenticatedProviderCoordinationRepresentativesRepresentativeIdRouteImport
      parentRoute: typeof AuthenticatedProviderCoordinationRouteRoute
    }
  }
}

interface AuthenticatedProviderCoordinationRouteRouteChildren {
  AuthenticatedProviderCoordinationCalendarRoute: typeof AuthenticatedProviderCoordinationCalendarRoute
  AuthenticatedProviderCoordinationMatchingRoute: typeof AuthenticatedProviderCoordinationMatchingRoute
  AuthenticatedProviderCoordinationIndexRoute: typeof AuthenticatedProviderCoordinationIndexRoute
  AuthenticatedProviderCoordinationProvidersProviderIdRoute: typeof AuthenticatedProviderCoordinationProvidersProviderIdRoute
  AuthenticatedProviderCoordinationRepresentativesRepresentativeIdRoute: typeof AuthenticatedProviderCoordinationRepresentativesRepresentativeIdRoute
  AuthenticatedProviderCoordinationProvidersIndexRoute: typeof AuthenticatedProviderCoordinationProvidersIndexRoute
  AuthenticatedProviderCoordinationRepresentativesIndexRoute: typeof AuthenticatedProviderCoordinationRepresentativesIndexRoute
}

const AuthenticatedProviderCoordinationRouteRouteChildren: AuthenticatedProviderCoordinationRouteRouteChildren =
  {
    AuthenticatedProviderCoordinationCalendarRoute:
      AuthenticatedProviderCoordinationCalendarRoute,
    AuthenticatedProviderCoordinationMatchingRoute:
      AuthenticatedProviderCoordinationMatchingRoute,
    AuthenticatedProviderCoordinationIndexRoute:
      AuthenticatedProviderCoordinationIndexRoute,
    AuthenticatedProviderCoordinationProvidersProviderIdRoute:
      AuthenticatedProviderCoordinationProvidersProviderIdRoute,
    AuthenticatedProviderCoordinationRepresentativesRepresentativeIdRoute:
      AuthenticatedProviderCoordinationRepresentativesRepresentativeIdRoute,
    AuthenticatedProviderCoordinationProvidersIndexRoute:
      AuthenticatedProviderCoordinationProvidersIndexRoute,
    AuthenticatedProviderCoordinationRepresentativesIndexRoute:
      AuthenticatedProviderCoordinationRepresentativesIndexRoute,
  }

const AuthenticatedProviderCoordinationRouteRouteWithChildren =
  AuthenticatedProviderCoordinationRouteRoute._addFileChildren(
    AuthenticatedProviderCoordinationRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProviderCoordinationRouteRoute: typeof AuthenticatedProviderCoordinationRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedFollowUpsRoute: typeof AuthenticatedFollowUpsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedApprovalsApprovalIdRoute: typeof AuthenticatedApprovalsApprovalIdRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedMaintenanceAiAgentRoute: typeof AuthenticatedMaintenanceAiAgentRoute
  AuthenticatedMaintenanceCatalogRoute: typeof AuthenticatedMaintenanceCatalogRoute
  AuthenticatedMaintenanceJobsRoute: typeof AuthenticatedMaintenanceJobsRoute
  AuthenticatedMaintenanceReportsRoute: typeof AuthenticatedMaintenanceReportsRoute
  AuthenticatedQuotationsCompareRoute: typeof AuthenticatedQuotationsCompareRoute
  AuthenticatedInspectionsIndexRoute: typeof AuthenticatedInspectionsIndexRoute
  AuthenticatedMaintenanceIndexRoute: typeof AuthenticatedMaintenanceIndexRoute
  AuthenticatedQuotationsIndexRoute: typeof AuthenticatedQuotationsIndexRoute
  AuthenticatedApprovalsIndexRoute: typeof AuthenticatedApprovalsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProviderCoordinationRouteRoute:
    AuthenticatedProviderCoordinationRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedFollowUpsRoute: AuthenticatedFollowUpsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedApprovalsApprovalIdRoute: AuthenticatedApprovalsApprovalIdRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedMaintenanceAiAgentRoute: AuthenticatedMaintenanceAiAgentRoute,
  AuthenticatedMaintenanceCatalogRoute: AuthenticatedMaintenanceCatalogRoute,
  AuthenticatedMaintenanceJobsRoute: AuthenticatedMaintenanceJobsRoute,
  AuthenticatedMaintenanceReportsRoute: AuthenticatedMaintenanceReportsRoute,
  AuthenticatedQuotationsCompareRoute: AuthenticatedQuotationsCompareRoute,
  AuthenticatedInspectionsIndexRoute: AuthenticatedInspectionsIndexRoute,
  AuthenticatedMaintenanceIndexRoute: AuthenticatedMaintenanceIndexRoute,
  AuthenticatedQuotationsIndexRoute: AuthenticatedQuotationsIndexRoute,
  AuthenticatedApprovalsIndexRoute: AuthenticatedApprovalsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
